"""
Core tables.

Node          — one row per physical (or simulated) drain sensor.
Reading       — one row per uplink payload received from a node.
Alert         — dispatched tickets / flood warnings generated by the
                decision engine.
RegionMode    — the current sampling mode (1/2/3) the weather sync
                service wants each municipality's nodes running at.
"""
from datetime import datetime, timezone

from sqlalchemy import (
    Column, Integer, String, Float, Boolean, DateTime, ForeignKey, JSON,
    PrimaryKeyConstraint,
)
from sqlalchemy.orm import relationship

from .database import Base


def utcnow():
    return datetime.now(timezone.utc)


class Node(Base):
    __tablename__ = "nodes"

    id = Column(String, primary_key=True)          # e.g. "TUN-ARIANA-014"
    municipality = Column(String, index=True)        # Tunis / Sfax / Sousse / Nabeul
    latitude = Column(Float)
    longitude = Column(Float)
    last_seen = Column(DateTime, default=utcnow)
    battery_v = Column(Float, default=3.6)
    current_mode = Column(Integer, default=1)         # 1=dry, 2=pre-storm, 3=storm
    status = Column(String, default="normal")          # normal / trash_flagged / silt_flagged / overflow_risk

    readings = relationship("Reading", back_populates="node", cascade="all, delete-orphan")
    alerts = relationship("Alert", back_populates="node", cascade="all, delete-orphan")


class Reading(Base):
    __tablename__ = "readings"

    # TimescaleDB requires every unique key on a hypertable to include its
    # partitioning column. Keep the generated reading id, but make the key
    # composite with timestamp.
    id = Column(Integer, autoincrement=True)
    node_id = Column(String, ForeignKey("nodes.id"), index=True)
    timestamp = Column(DateTime, default=utcnow, index=True, nullable=False)
    mode = Column(Integer)
    battery_v = Column(Float)
    moisture_switch = Column(Boolean, default=False)
    distance_cm = Column(Float, nullable=True)
    dh_dt = Column(Float, nullable=True)               # rate of water-level rise, cm/min

    classifier_class = Column(String, nullable=True)   # empty / solid_trash / organic_silt / false_positive
    classifier_confidence = Column(Float, nullable=True)
    p_trash = Column(Float, nullable=True)

    __table_args__ = (PrimaryKeyConstraint("id", "timestamp"),)

    node = relationship("Node", back_populates="readings")


class Alert(Base):
    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    node_id = Column(String, ForeignKey("nodes.id"), index=True)
    created_at = Column(DateTime, default=utcnow)
    alert_type = Column(String)                        # cleaning_ticket / overflow_warning
    priority = Column(String, default="normal")          # normal / high / critical
    message = Column(String)
    eta_minutes = Column(Float, nullable=True)          # for overflow warnings
    acknowledged = Column(Boolean, default=False)
    acknowledged_at = Column(DateTime, nullable=True)
    meta = Column(JSON, nullable=True)

    node = relationship("Node", back_populates="alerts")


class RegionMode(Base):
    __tablename__ = "region_modes"

    municipality = Column(String, primary_key=True)
    mode = Column(Integer, default=1)
    rain_probability = Column(Float, nullable=True)
    rain_rate_mm_h = Column(Float, nullable=True)
    updated_at = Column(DateTime, default=utcnow)
